// sidebars.union.js
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  unionSidebar: [
    { type: 'autogenerated', dirName: '.' }
  ],
};

export default sidebars;
